// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/distill/pkg/distill"
)

type DistillParser struct {
	ParseStub        func(context.Context, string) ([]distill.Rule, error)
	parseMutex       sync.RWMutex
	parseArgsForCall []DistillParserParseArgs
	parseReturns     struct {
		result1 []distill.Rule
		result2 error
	}
	parseReturnsOnCall map[int]struct {
		result1 []distill.Rule
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// DistillParserParseArgs holds the arguments of one call to Parse.
type DistillParserParseArgs struct {
	Arg1 context.Context
	Arg2 string
}

func (fake *DistillParser) Parse(arg1 context.Context, arg2 string) ([]distill.Rule, error) {
	fake.parseMutex.Lock()
	ret, specificReturn := fake.parseReturnsOnCall[len(fake.parseArgsForCall)]
	fake.parseArgsForCall = append(fake.parseArgsForCall, DistillParserParseArgs{arg1, arg2})
	stub := fake.ParseStub
	fakeReturns := fake.parseReturns
	fake.recordInvocation("Parse", []interface{}{arg1, arg2})
	fake.parseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *DistillParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *DistillParser) ParseCalls(stub func(context.Context, string) ([]distill.Rule, error)) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = stub
}

func (fake *DistillParser) ParseArgsForCall(i int) (context.Context, string) {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	argsForCall := fake.parseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *DistillParser) ParseArgs() []DistillParserParseArgs {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	args := make([]DistillParserParseArgs, len(fake.parseArgsForCall))
	copy(args, fake.parseArgsForCall)
	return args
}

func (fake *DistillParser) ParseReturns(result1 []distill.Rule, result2 error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 []distill.Rule
		result2 error
	}{result1, result2}
}

func (fake *DistillParser) ParseReturnsOnCall(i int, result1 []distill.Rule, result2 error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	if fake.parseReturnsOnCall == nil {
		fake.parseReturnsOnCall = make(map[int]struct {
			result1 []distill.Rule
			result2 error
		})
	}
	fake.parseReturnsOnCall[i] = struct {
		result1 []distill.Rule
		result2 error
	}{result1, result2}
}

func (fake *DistillParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DistillParser) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *DistillParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ distill.Parser = new(DistillParser)
