// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/distill/pkg/distill"
)

type DistillCache struct {
	GetStub        func(string, string) (string, bool)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getReturns struct {
		result1 string
		result2 bool
	}
	getReturnsOnCall map[int]struct {
		result1 string
		result2 bool
	}
	LoadStub        func(context.Context) error
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
	}
	loadReturns struct {
		result1 error
	}
	loadReturnsOnCall map[int]struct {
		result1 error
	}
	PutStub        func(string, string, string)
	putMutex       sync.RWMutex
	putArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	RuleHashStub        func(string, string) string
	ruleHashMutex       sync.RWMutex
	ruleHashArgsForCall []struct {
		arg1 string
		arg2 string
	}
	ruleHashReturns struct {
		result1 string
	}
	ruleHashReturnsOnCall map[int]struct {
		result1 string
	}
	SaveStub        func(context.Context, []string) error
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	saveReturns struct {
		result1 error
	}
	saveReturnsOnCall map[int]struct {
		result1 error
	}
	SaveMergedStub        func(context.Context) error
	saveMergedMutex       sync.RWMutex
	saveMergedArgsForCall []struct {
		arg1 context.Context
	}
	saveMergedReturns struct {
		result1 error
	}
	saveMergedReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DistillCache) Get(arg1 string, arg2 string) (string, bool) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *DistillCache) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *DistillCache) GetCalls(stub func(string, string) (string, bool)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *DistillCache) GetArgsForCall(i int) (string, string) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *DistillCache) GetReturns(result1 string, result2 bool) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *DistillCache) GetReturnsOnCall(i int, result1 string, result2 bool) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *DistillCache) Load(arg1 context.Context) error {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *DistillCache) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *DistillCache) LoadCalls(stub func(context.Context) error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *DistillCache) LoadArgsForCall(i int) context.Context {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1
}

func (fake *DistillCache) LoadReturns(result1 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 error
	}{result1}
}

func (fake *DistillCache) LoadReturnsOnCall(i int, result1 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *DistillCache) Put(arg1 string, arg2 string, arg3 string) {
	fake.putMutex.Lock()
	fake.putArgsForCall = append(fake.putArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PutStub
	fake.recordInvocation("Put", []interface{}{arg1, arg2, arg3})
	fake.putMutex.Unlock()
	if stub != nil {
		fake.PutStub(arg1, arg2, arg3)
	}
}

func (fake *DistillCache) PutCallCount() int {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	return len(fake.putArgsForCall)
}

func (fake *DistillCache) PutCalls(stub func(string, string, string)) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = stub
}

func (fake *DistillCache) PutArgsForCall(i int) (string, string, string) {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	argsForCall := fake.putArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *DistillCache) RuleHash(arg1 string, arg2 string) string {
	fake.ruleHashMutex.Lock()
	ret, specificReturn := fake.ruleHashReturnsOnCall[len(fake.ruleHashArgsForCall)]
	fake.ruleHashArgsForCall = append(fake.ruleHashArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.RuleHashStub
	fakeReturns := fake.ruleHashReturns
	fake.recordInvocation("RuleHash", []interface{}{arg1, arg2})
	fake.ruleHashMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *DistillCache) RuleHashCallCount() int {
	fake.ruleHashMutex.RLock()
	defer fake.ruleHashMutex.RUnlock()
	return len(fake.ruleHashArgsForCall)
}

func (fake *DistillCache) RuleHashCalls(stub func(string, string) string) {
	fake.ruleHashMutex.Lock()
	defer fake.ruleHashMutex.Unlock()
	fake.RuleHashStub = stub
}

func (fake *DistillCache) RuleHashArgsForCall(i int) (string, string) {
	fake.ruleHashMutex.RLock()
	defer fake.ruleHashMutex.RUnlock()
	argsForCall := fake.ruleHashArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *DistillCache) RuleHashReturns(result1 string) {
	fake.ruleHashMutex.Lock()
	defer fake.ruleHashMutex.Unlock()
	fake.RuleHashStub = nil
	fake.ruleHashReturns = struct {
		result1 string
	}{result1}
}

func (fake *DistillCache) RuleHashReturnsOnCall(i int, result1 string) {
	fake.ruleHashMutex.Lock()
	defer fake.ruleHashMutex.Unlock()
	fake.RuleHashStub = nil
	if fake.ruleHashReturnsOnCall == nil {
		fake.ruleHashReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.ruleHashReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *DistillCache) Save(arg1 context.Context, arg2 []string) error {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.saveMutex.Lock()
	ret, specificReturn := fake.saveReturnsOnCall[len(fake.saveArgsForCall)]
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.SaveStub
	fakeReturns := fake.saveReturns
	fake.recordInvocation("Save", []interface{}{arg1, arg2Copy})
	fake.saveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *DistillCache) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *DistillCache) SaveCalls(stub func(context.Context, []string) error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = stub
}

func (fake *DistillCache) SaveArgsForCall(i int) (context.Context, []string) {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	argsForCall := fake.saveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *DistillCache) SaveReturns(result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 error
	}{result1}
}

func (fake *DistillCache) SaveReturnsOnCall(i int, result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	if fake.saveReturnsOnCall == nil {
		fake.saveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *DistillCache) SaveMerged(arg1 context.Context) error {
	fake.saveMergedMutex.Lock()
	ret, specificReturn := fake.saveMergedReturnsOnCall[len(fake.saveMergedArgsForCall)]
	fake.saveMergedArgsForCall = append(fake.saveMergedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SaveMergedStub
	fakeReturns := fake.saveMergedReturns
	fake.recordInvocation("SaveMerged", []interface{}{arg1})
	fake.saveMergedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *DistillCache) SaveMergedCallCount() int {
	fake.saveMergedMutex.RLock()
	defer fake.saveMergedMutex.RUnlock()
	return len(fake.saveMergedArgsForCall)
}

func (fake *DistillCache) SaveMergedCalls(stub func(context.Context) error) {
	fake.saveMergedMutex.Lock()
	defer fake.saveMergedMutex.Unlock()
	fake.SaveMergedStub = stub
}

func (fake *DistillCache) SaveMergedArgsForCall(i int) context.Context {
	fake.saveMergedMutex.RLock()
	defer fake.saveMergedMutex.RUnlock()
	argsForCall := fake.saveMergedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *DistillCache) SaveMergedReturns(result1 error) {
	fake.saveMergedMutex.Lock()
	defer fake.saveMergedMutex.Unlock()
	fake.SaveMergedStub = nil
	fake.saveMergedReturns = struct {
		result1 error
	}{result1}
}

func (fake *DistillCache) SaveMergedReturnsOnCall(i int, result1 error) {
	fake.saveMergedMutex.Lock()
	defer fake.saveMergedMutex.Unlock()
	fake.SaveMergedStub = nil
	if fake.saveMergedReturnsOnCall == nil {
		fake.saveMergedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveMergedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *DistillCache) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DistillCache) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ distill.Cache = new(DistillCache)
