#!/bin/bash
# PreToolUse hook: deny Edit/Write/NotebookEdit on distill-generated files
# (edits clobbered on next `distill` run; source of truth is the rule source dir).
#
# Detection is content-based, not path-based: any file whose header carries the
# "AUTO-GENERATED by distill" banner is protected, wherever it lives. The banner
# also carries `Source:` and `Regenerate:` lines, so the denial message can quote
# the file's own regenerate command instead of hardcoding paths.

set -e
input=$(cat)
tool=$(jq -r '.tool_name' <<<"$input")

passthrough() {
  jq -n '{hookSpecificOutput:{hookEventName:"PreToolUse"}}'
  exit 0
}

deny() {
  jq -n --arg msg "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$msg}}'
  exit 0
}

case "$tool" in
  Edit|Write|NotebookEdit)
    path=$(jq -r '.tool_input.file_path // empty' <<<"$input")

    # Nothing to protect if the file doesn't exist yet (Write of a new file).
    [ -n "$path" ] && [ -f "$path" ] || passthrough

    # Banner lives in the first few lines; cap the read so this stays cheap.
    header=$(head -c 2048 "$path" 2>/dev/null || true)
    grep -qi 'AUTO-GENERATED by distill' <<<"$header" || passthrough

    source_dir=$(grep -oE 'Source:[[:space:]]*\S+' <<<"$header" | head -1 | sed -E 's/^Source:[[:space:]]*//')
    regen=$(grep -oE 'Regenerate:[[:space:]]*.+' <<<"$header" | head -1 | sed -E 's/^Regenerate:[[:space:]]*//')

    msg="Refused: $path is AUTO-GENERATED by distill — edits are clobbered on the next run."
    if [ -n "$source_dir" ]; then
      msg="$msg Edit the rule source in $source_dir/<rule-id>.md instead (one file per rule; the \`distill:\` frontmatter sets section + order)."
    else
      msg="$msg Edit the rule source dir named in the file's own header banner instead."
    fi
    if [ -n "$regen" ]; then
      msg="$msg Then regenerate: $regen"
    else
      msg="$msg Then regenerate with the command in the file's header banner."
    fi
    deny "$msg"
    ;;
  *)
    passthrough
    ;;
esac
