// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package distill_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/bborbe/distill/mocks"
	"github.com/bborbe/distill/pkg/distill"
)

// stubRunnerWith builds a Counterfeiter-generated DistillRunner whose Run
// returns a body keyed on the rule id embedded in the prompt — keeping the
// behavioural e2e tests readable while still exercising the generated mock.
func stubRunnerWith(byID map[string]string) *mocks.DistillRunner {
	runner := &mocks.DistillRunner{}
	runner.RunStub = func(_ context.Context, _ string, _ string, prompt string) (string, error) {
		for id, body := range byID {
			if strings.Contains(prompt, "id="+id) {
				return body, nil
			}
		}
		return "- (no match)", nil
	}
	return runner
}

// promptsSeen returns every prompt the runner was called with, in call order.
func promptsSeen(r *mocks.DistillRunner) []string {
	out := make([]string, r.RunCallCount())
	for i := 0; i < r.RunCallCount(); i++ {
		_, _, _, prompt := r.RunArgsForCall(i)
		out[i] = prompt
	}
	return out
}

var _ = Describe("Driver", func() {
	var (
		ctx        context.Context
		tempDir    string
		sourceDir  string
		outputPath string
	)

	BeforeEach(func() {
		ctx = context.Background()
		var err error
		tempDir, err = os.MkdirTemp("", "distill-e2e-*")
		Expect(err).NotTo(HaveOccurred())
		sourceDir = filepath.Join(tempDir, "sources")
		Expect(os.Mkdir(sourceDir, 0o755)).To(Succeed())
		outputPath = filepath.Join(tempDir, "out.md")
	})

	AfterEach(func() {
		_ = os.RemoveAll(tempDir)
	})

	writeSource := func(name, content string) {
		Expect(os.WriteFile(filepath.Join(sourceDir, name), []byte(content), 0o644)).To(Succeed())
	}
	readOutput := func() string {
		b, err := os.ReadFile(outputPath)
		Expect(err).NotTo(HaveOccurred())
		return string(b)
	}

	newDriver := func(stub *mocks.DistillRunner, title string) *distill.Driver {
		return &distill.Driver{
			Parser: distill.NewParser(),
			Runner: stub,
			Writer: distill.NewWriter(),
			Stderr: GinkgoWriter,
			Title:  title,
		}
	}

	It("emits the auto-generated warning + title + section heading + bullets", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n  id: a\n---\nbody A\n")
		stub := stubRunnerWith(map[string]string{"a": "- **A.** compressed A"})
		Expect(newDriver(stub, "Global Preferences").Run(ctx, sourceDir, outputPath)).To(Succeed())
		got := readOutput()
		Expect(got).To(HavePrefix("<!--\n  AUTO-GENERATED by distill"))
		Expect(got).To(ContainSubstring("Source: " + sourceDir))
		Expect(got).To(ContainSubstring("\n# Global Preferences\n"))
		Expect(got).To(ContainSubstring("\n## Git\n\n- **A.** compressed A\n"))
	})

	It("omits the title heading when --title is empty", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n---\nbody\n")
		stub := stubRunnerWith(map[string]string{"a": "- one"})
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		got := readOutput()
		Expect(got).NotTo(ContainSubstring("\n# "))
	})

	It("groups rules into one prompt per section in (order, id) order", func() {
		writeSource(
			"late.md",
			"---\ndistill:\n  section: Git\n  order: 20\n  id: rule-late\n---\nbody late\n",
		)
		writeSource(
			"early.md",
			"---\ndistill:\n  section: Git\n  order: 10\n  id: rule-early\n---\nbody early\n",
		)
		stub := stubRunnerWith(map[string]string{"rule-early": "- early; - late"})
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(promptsSeen(stub)).To(HaveLen(1))
		prompt := promptsSeen(stub)[0]
		idxEarly := strings.Index(prompt, "id=rule-early")
		idxLate := strings.Index(prompt, "id=rule-late")
		Expect(idxEarly).To(BeNumerically(">=", 0))
		Expect(idxLate).To(BeNumerically(">", idxEarly))
	})

	It("sorts sections by minimum order then alphabetically", func() {
		writeSource("git-rule.md", "---\ndistill:\n  section: Git\n  order: 50\n---\nbody\n")
		writeSource("op-rule.md", "---\ndistill:\n  section: Operational\n  order: 10\n---\nbody\n")
		writeSource("common-rule.md", "---\ndistill:\n  section: Common\n  order: 10\n---\nbody\n")
		stub := stubRunnerWith(nil)
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		got := readOutput()
		idxCommon := strings.Index(got, "## Common")
		idxOp := strings.Index(got, "## Operational")
		idxGit := strings.Index(got, "## Git")
		Expect(idxCommon).To(BeNumerically(">=", 0))
		Expect(idxOp).To(BeNumerically(">", idxCommon))
		Expect(idxGit).To(BeNumerically(">", idxOp))
	})

	It("skips source files without a distill: frontmatter block", func() {
		writeSource("docs.md", "---\ntitle: docs\n---\nnot a rule\n")
		writeSource("rule.md", "---\ndistill:\n  section: Git\n---\nbody\n")
		stub := stubRunnerWith(map[string]string{"rule": "- ok"})
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(promptsSeen(stub)).To(HaveLen(1))
	})

	It("excludes disabled rules from prompts and output", func() {
		writeSource("keep.md", "---\ndistill:\n  section: Git\n  id: keep\n---\nbody keep\n")
		writeSource(
			"drop.md",
			"---\ndistill:\n  section: Git\n  id: drop\n  disabled: true\n---\nbody drop\n",
		)
		stub := stubRunnerWith(map[string]string{"keep": "- only keep"})
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(promptsSeen(stub)).To(HaveLen(1))
		Expect(promptsSeen(stub)[0]).NotTo(ContainSubstring("id=drop"))
	})

	It("errors when distill.section is missing", func() {
		writeSource("a.md", "---\ndistill:\n  order: 10\n---\nbody\n")
		err := newDriver(stubRunnerWith(nil), "").Run(ctx, sourceDir, outputPath)
		Expect(err).To(HaveOccurred())
		Expect(err.Error()).To(ContainSubstring("distill.section is required"))
	})

	It("errors on duplicate (section, order, id)", func() {
		writeSource("d1.md", "---\ndistill:\n  section: Git\n  id: same\n  order: 10\n---\nbody\n")
		writeSource("d2.md", "---\ndistill:\n  section: Git\n  id: same\n  order: 10\n---\nbody\n")
		err := newDriver(stubRunnerWith(nil), "").Run(ctx, sourceDir, outputPath)
		Expect(err).To(HaveOccurred())
		Expect(err.Error()).To(ContainSubstring("duplicate"))
	})

	It("regenerates the output file from scratch (overwrites prior content)", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n---\nbody\n")
		Expect(
			os.WriteFile(outputPath, []byte("OLD STALE CONTENT\nshould vanish\n"), 0o644),
		).To(Succeed())
		stub := stubRunnerWith(map[string]string{"a": "- new bullet"})
		Expect(newDriver(stub, "T").Run(ctx, sourceDir, outputPath)).To(Succeed())
		got := readOutput()
		Expect(got).NotTo(ContainSubstring("OLD STALE CONTENT"))
		Expect(got).To(ContainSubstring("- new bullet"))
	})
})
