// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package distill_test

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/bborbe/distill/mocks"
	"github.com/bborbe/distill/pkg/distill"
)

// stubRunnerWith builds a DistillRunner whose Run inspects the prompt for
// <rule id="X"> occurrences and returns one "--- bullet id=X ---\n<bullet>\n"
// block per found id. When byID[id] is set, that bullet text is used; otherwise
// a valid placeholder "- **X.** placeholder" is emitted so the run succeeds.
func stubRunnerWith(byID map[string]string) *mocks.DistillRunner {
	runner := &mocks.DistillRunner{}
	runner.RunStub = func(_ context.Context, _ string, _ string, prompt string) (string, error) {
		var sb strings.Builder
		remaining := prompt
		for {
			const prefix = `<rule id="`
			start := strings.Index(remaining, prefix)
			if start < 0 {
				break
			}
			remaining = remaining[start+len(prefix):]
			end := strings.Index(remaining, `"`)
			if end < 0 {
				break
			}
			id := remaining[:end]
			remaining = remaining[end+1:]

			sb.WriteString("--- bullet id=")
			sb.WriteString(id)
			sb.WriteString(" ---\n")
			if bullet, ok := byID[id]; ok {
				sb.WriteString(bullet)
			} else {
				sb.WriteString("- **")
				sb.WriteString(id)
				sb.WriteString(".** placeholder")
			}
			sb.WriteString("\n")
		}
		return sb.String(), nil
	}
	return runner
}

// alwaysMissCache returns a mock Cache whose Get always misses and RuleHash
// returns a deterministic hash. Used with NoCache: true so only RuleHash and
// Put are actually called.
func alwaysMissCache() *mocks.DistillCache {
	c := &mocks.DistillCache{}
	c.RuleHashStub = func(model, body string) string {
		return "hash-" + body
	}
	c.GetStub = func(id, hash string) (string, bool) {
		return "", false
	}
	return c
}

// promptsSeen returns every user prompt the runner was called with, in call order.
func promptsSeen(r *mocks.DistillRunner) []string {
	out := make([]string, r.RunCallCount())
	for i := 0; i < r.RunCallCount(); i++ {
		_, _, _, prompt := r.RunArgsForCall(i)
		out[i] = prompt
	}
	return out
}

var _ = Describe("Driver", func() {
	var (
		ctx        context.Context
		tempDir    string
		sourceDir  string
		outputPath string
	)

	BeforeEach(func() {
		ctx = context.Background()
		var err error
		tempDir, err = os.MkdirTemp("", "distill-e2e-*")
		Expect(err).NotTo(HaveOccurred())
		sourceDir = filepath.Join(tempDir, "sources")
		Expect(os.Mkdir(sourceDir, 0o755)).To(Succeed())
		outputPath = filepath.Join(tempDir, "out.md")
	})

	AfterEach(func() {
		_ = os.RemoveAll(tempDir)
	})

	writeSource := func(name, content string) {
		Expect(os.WriteFile(filepath.Join(sourceDir, name), []byte(content), 0o644)).To(Succeed())
	}
	readOutput := func() string {
		b, err := os.ReadFile(outputPath)
		Expect(err).NotTo(HaveOccurred())
		return string(b)
	}

	newDriver := func(stub *mocks.DistillRunner, title string) *distill.Driver {
		return &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    stub,
			Writer:    distill.NewWriter(),
			Stderr:    GinkgoWriter,
			Title:     title,
			NoCache:   true,
			BatchSize: 100,
			Cache:     alwaysMissCache(),
		}
	}

	It("emits the auto-generated warning + title + section heading + bullets", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n  id: a\n---\nbody A\n")
		stub := stubRunnerWith(map[string]string{"a": "- **A.** compressed A"})
		Expect(newDriver(stub, "Global Preferences").Run(ctx, sourceDir, outputPath)).To(Succeed())
		got := readOutput()
		Expect(got).To(HavePrefix("<!--\n  AUTO-GENERATED by distill"))
		Expect(got).To(ContainSubstring("Source: " + sourceDir))
		Expect(got).To(ContainSubstring("\n# Global Preferences\n"))
		Expect(got).To(ContainSubstring("\n## Git\n\n- **A.** compressed A\n"))
	})

	It("omits the title heading when --title is empty", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n---\nbody\n")
		stub := stubRunnerWith(map[string]string{"a": "- **A.** one"})
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		got := readOutput()
		Expect(got).NotTo(ContainSubstring("\n# "))
	})

	It("groups rules into one prompt per chunk in (order, id) order", func() {
		writeSource(
			"late.md",
			"---\ndistill:\n  section: Git\n  order: 20\n  id: rule-late\n---\nbody late\n",
		)
		writeSource(
			"early.md",
			"---\ndistill:\n  section: Git\n  order: 10\n  id: rule-early\n---\nbody early\n",
		)
		stub := stubRunnerWith(nil)
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(promptsSeen(stub)).To(HaveLen(1))
		prompt := promptsSeen(stub)[0]
		idxEarly := strings.Index(prompt, `id="rule-early"`)
		idxLate := strings.Index(prompt, `id="rule-late"`)
		Expect(idxEarly).To(BeNumerically(">=", 0))
		Expect(idxLate).To(BeNumerically(">", idxEarly))
	})

	It("sorts sections by minimum order then alphabetically", func() {
		writeSource("git-rule.md", "---\ndistill:\n  section: Git\n  order: 50\n---\nbody\n")
		writeSource("op-rule.md", "---\ndistill:\n  section: Operational\n  order: 10\n---\nbody\n")
		writeSource("common-rule.md", "---\ndistill:\n  section: Common\n  order: 10\n---\nbody\n")
		stub := stubRunnerWith(nil)
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		got := readOutput()
		idxCommon := strings.Index(got, "## Common")
		idxOp := strings.Index(got, "## Operational")
		idxGit := strings.Index(got, "## Git")
		Expect(idxCommon).To(BeNumerically(">=", 0))
		Expect(idxOp).To(BeNumerically(">", idxCommon))
		Expect(idxGit).To(BeNumerically(">", idxOp))
	})

	It("skips source files without a distill: frontmatter block", func() {
		writeSource("docs.md", "---\ntitle: docs\n---\nnot a rule\n")
		writeSource("rule.md", "---\ndistill:\n  section: Git\n---\nbody\n")
		stub := stubRunnerWith(map[string]string{"rule": "- **Rule.** ok"})
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(promptsSeen(stub)).To(HaveLen(1))
	})

	It("excludes disabled rules from prompts and output", func() {
		writeSource("keep.md", "---\ndistill:\n  section: Git\n  id: keep\n---\nbody keep\n")
		writeSource(
			"drop.md",
			"---\ndistill:\n  section: Git\n  id: drop\n  disabled: true\n---\nbody drop\n",
		)
		stub := stubRunnerWith(map[string]string{"keep": "- **Keep.** only keep"})
		Expect(newDriver(stub, "").Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(promptsSeen(stub)).To(HaveLen(1))
		Expect(promptsSeen(stub)[0]).NotTo(ContainSubstring(`id="drop"`))
	})

	It("errors when distill.section is missing", func() {
		writeSource("a.md", "---\ndistill:\n  order: 10\n---\nbody\n")
		err := newDriver(stubRunnerWith(nil), "").Run(ctx, sourceDir, outputPath)
		Expect(err).To(HaveOccurred())
		Expect(err.Error()).To(ContainSubstring("distill.section is required"))
	})

	It("errors on duplicate (section, order, id)", func() {
		writeSource("d1.md", "---\ndistill:\n  section: Git\n  id: same\n  order: 10\n---\nbody\n")
		writeSource("d2.md", "---\ndistill:\n  section: Git\n  id: same\n  order: 10\n---\nbody\n")
		err := newDriver(stubRunnerWith(nil), "").Run(ctx, sourceDir, outputPath)
		Expect(err).To(HaveOccurred())
		Expect(err.Error()).To(ContainSubstring("duplicate"))
	})

	It("regenerates the output file from scratch (overwrites prior content)", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n---\nbody\n")
		Expect(
			os.WriteFile(outputPath, []byte("OLD STALE CONTENT\nshould vanish\n"), 0o644),
		).To(Succeed())
		stub := stubRunnerWith(map[string]string{"a": "- **A.** new bullet"})
		Expect(newDriver(stub, "T").Run(ctx, sourceDir, outputPath)).To(Succeed())
		got := readOutput()
		Expect(got).NotTo(ContainSubstring("OLD STALE CONTENT"))
		Expect(got).To(ContainSubstring("- **A.** new bullet"))
	})

	It("hijack response leaves output file untouched and names unresolved ids", func() {
		writeSource("r1.md", "---\ndistill:\n  section: Git\n  id: r1\n---\nbody r1\n")
		// Pre-existing output with known bytes.
		preExisting := []byte("PRIOR OUTPUT\n")
		Expect(os.WriteFile(outputPath, preExisting, 0o644)).To(Succeed())

		// Hijack: runner returns zero delimiters on every call.
		hijackStub := &mocks.DistillRunner{}
		hijackStub.RunReturns("This is a refusal with no bullet delimiters.", nil)

		mockWriter := &mocks.DistillWriter{}
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    hijackStub,
			Writer:    mockWriter,
			Stderr:    GinkgoWriter,
			Title:     "",
			NoCache:   true,
			BatchSize: 100,
			Cache:     alwaysMissCache(),
		}
		err := driver.Run(ctx, sourceDir, outputPath)
		Expect(err).To(HaveOccurred())
		Expect(err.Error()).To(ContainSubstring("r1"))
		Expect(mockWriter.WriteCallCount()).To(Equal(0))

		// Pre-existing file is byte-identical.
		got, readErr := os.ReadFile(outputPath)
		Expect(readErr).NotTo(HaveOccurred())
		Expect(got).To(Equal(preExisting))
	})

	It("chunks rules into batches of BatchSize runner calls", func() {
		ids := []string{"a", "b", "c", "d", "e"}
		for i, name := range ids {
			writeSource(
				name+".md",
				fmt.Sprintf(
					"---\ndistill:\n  section: Git\n  id: %s\n  order: %d\n---\nbody %s\n",
					name, (i+1)*10, name,
				),
			)
		}
		stub := stubRunnerWith(nil)
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    stub,
			Writer:    distill.NewWriter(),
			Stderr:    GinkgoWriter,
			Title:     "",
			NoCache:   true,
			BatchSize: 2,
			Cache:     alwaysMissCache(),
		}
		Expect(driver.Run(ctx, sourceDir, outputPath)).To(Succeed())
		// ceil(5/2) = 3 runner calls.
		Expect(stub.RunCallCount()).To(Equal(3))
		// First chunk: a, b (order 10, 20).
		_, _, _, p0 := stub.RunArgsForCall(0)
		Expect(p0).To(ContainSubstring(`id="a"`))
		Expect(p0).To(ContainSubstring(`id="b"`))
		Expect(p0).NotTo(ContainSubstring(`id="c"`))
		// Second chunk: c, d.
		_, _, _, p1 := stub.RunArgsForCall(1)
		Expect(p1).To(ContainSubstring(`id="c"`))
		Expect(p1).To(ContainSubstring(`id="d"`))
		Expect(p1).NotTo(ContainSubstring(`id="e"`))
		// Third chunk: e.
		_, _, _, p2 := stub.RunArgsForCall(2)
		Expect(p2).To(ContainSubstring(`id="e"`))
	})

	It("retries an id whose first-pass bullet fails validation", func() {
		writeSource("r1.md", "---\ndistill:\n  section: Git\n  id: r1\n---\nbody r1\n")
		stub := &mocks.DistillRunner{}
		// First call: returns a bullet that fails ValidateBullet (no "- **" prefix).
		stub.RunReturnsOnCall(0, "--- bullet id=r1 ---\nplain text, not a bullet\n", nil)
		// Second call (retry): returns a valid bullet.
		stub.RunReturnsOnCall(1, "--- bullet id=r1 ---\n- **R1.** valid\n", nil)
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    stub,
			Writer:    distill.NewWriter(),
			Stderr:    GinkgoWriter,
			Title:     "",
			NoCache:   true,
			BatchSize: 100,
			Cache:     alwaysMissCache(),
		}
		Expect(driver.Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(stub.RunCallCount()).To(Equal(2))
	})

	It("retries only the failing ids in a scoped second call", func() {
		writeSource("r1.md", "---\ndistill:\n  section: Git\n  id: r1\n  order: 10\n---\nbody r1\n")
		writeSource("r2.md", "---\ndistill:\n  section: Git\n  id: r2\n  order: 20\n---\nbody r2\n")

		stub := &mocks.DistillRunner{}
		// First call: only returns r2 (omits r1).
		stub.RunReturnsOnCall(0, "--- bullet id=r2 ---\n- **R2.** body r2\n", nil)
		// Second call (retry for r1): returns r1.
		stub.RunReturnsOnCall(1, "--- bullet id=r1 ---\n- **R1.** body r1\n", nil)

		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    stub,
			Writer:    distill.NewWriter(),
			Stderr:    GinkgoWriter,
			Title:     "",
			NoCache:   true,
			BatchSize: 100,
			Cache:     alwaysMissCache(),
		}
		Expect(driver.Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(stub.RunCallCount()).To(Equal(2))

		// Second prompt must contain only r1, not r2.
		_, _, _, secondPrompt := stub.RunArgsForCall(1)
		Expect(secondPrompt).To(ContainSubstring(`id="r1"`))
		Expect(secondPrompt).NotTo(ContainSubstring(`id="r2"`))

		// Output contains both bullets.
		got := readOutput()
		Expect(got).To(ContainSubstring("- **R1.** body r1"))
		Expect(got).To(ContainSubstring("- **R2.** body r2"))
	})

	It("prints a summary line to stderr", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n  id: a\n---\nbody\n")
		stub := stubRunnerWith(nil)
		var stderrBuf bytes.Buffer
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    stub,
			Writer:    distill.NewWriter(),
			Stderr:    &stderrBuf,
			Title:     "",
			NoCache:   true,
			BatchSize: 100,
			Cache:     alwaysMissCache(),
		}
		Expect(driver.Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(stderrBuf.String()).To(MatchRegexp(
			`distill: \d+ cached, \d+ compiled \(\d+ chunks\), \d+ retried`,
		))
	})

	It("returns an error and does not call Writer when the runner fails", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n  id: a\n---\nbody\n")
		errStub := &mocks.DistillRunner{}
		errStub.RunReturns("", fmt.Errorf("claude failed"))
		mockWriter := &mocks.DistillWriter{}
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    errStub,
			Writer:    mockWriter,
			Stderr:    GinkgoWriter,
			Title:     "",
			NoCache:   true,
			BatchSize: 100,
			Cache:     alwaysMissCache(),
		}
		err := driver.Run(ctx, sourceDir, outputPath)
		Expect(err).To(HaveOccurred())
		Expect(mockWriter.WriteCallCount()).To(Equal(0))
	})

	It("returns an error when Writer.Write fails", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n  id: a\n---\nbody\n")
		stub := stubRunnerWith(nil)
		mockWriter := &mocks.DistillWriter{}
		mockWriter.WriteReturns(fmt.Errorf("disk full"))
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    stub,
			Writer:    mockWriter,
			Stderr:    GinkgoWriter,
			Title:     "",
			NoCache:   true,
			BatchSize: 100,
			Cache:     alwaysMissCache(),
		}
		Expect(driver.Run(ctx, sourceDir, outputPath)).To(MatchError(ContainSubstring("disk full")))
	})

	It("warns to stderr when cache Load returns an error and continues cold", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n  id: a\n---\nbody\n")
		stub := stubRunnerWith(nil)
		cache := &mocks.DistillCache{}
		cache.RuleHashStub = func(model, body string) string { return "h" }
		cache.LoadReturns(fmt.Errorf("corrupt cache"))
		cache.GetStub = func(id, hash string) (string, bool) { return "", false }
		var stderrBuf bytes.Buffer
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    stub,
			Writer:    distill.NewWriter(),
			Stderr:    &stderrBuf,
			Title:     "",
			NoCache:   false,
			BatchSize: 100,
			Cache:     cache,
		}
		Expect(driver.Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(stderrBuf.String()).To(ContainSubstring("cache load warning"))
		// Runner was called because the cache was cold (all misses).
		Expect(stub.RunCallCount()).To(Equal(1))
	})

	It("calls Cache.Save with enabled ids on a successful run when NoCache=false", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n  id: a\n---\nbody\n")
		stub := stubRunnerWith(nil)
		cache := &mocks.DistillCache{}
		cache.RuleHashStub = func(model, body string) string { return "h" }
		cache.GetStub = func(id, hash string) (string, bool) { return "", false }
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    stub,
			Writer:    distill.NewWriter(),
			Stderr:    GinkgoWriter,
			Title:     "",
			NoCache:   false,
			BatchSize: 100,
			Cache:     cache,
		}
		Expect(driver.Run(ctx, sourceDir, outputPath)).To(Succeed())
		Expect(cache.SaveCallCount()).To(Equal(1))
		_, keepIDs := cache.SaveArgsForCall(0)
		Expect(keepIDs).To(ConsistOf("a"))
	})

	It("calls Cache.SaveMerged (not Save) on compile failure when NoCache=false", func() {
		writeSource("a.md", "---\ndistill:\n  section: Git\n  id: a\n---\nbody\n")
		// Runner always returns zero delimiters → compile fails.
		errStub := &mocks.DistillRunner{}
		errStub.RunReturns("no delimiters here", nil)
		cache := &mocks.DistillCache{}
		cache.RuleHashStub = func(model, body string) string { return "h" }
		cache.GetStub = func(id, hash string) (string, bool) { return "", false }
		driver := &distill.Driver{
			Parser:    distill.NewParser(),
			Runner:    errStub,
			Writer:    distill.NewWriter(),
			Stderr:    GinkgoWriter,
			Title:     "",
			NoCache:   false,
			BatchSize: 100,
			Cache:     cache,
		}
		Expect(driver.Run(ctx, sourceDir, outputPath)).To(HaveOccurred())
		Expect(cache.SaveMergedCallCount()).To(Equal(1))
		Expect(cache.SaveCallCount()).To(Equal(0))
	})

	Describe("ExitCode", func() {
		It("returns 0 for nil error", func() {
			Expect(distill.ExitCode(nil)).To(Equal(0))
		})
		It("returns 1 for non-nil error", func() {
			Expect(distill.ExitCode(fmt.Errorf("oops"))).To(Equal(1))
		})
	})
})
