// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package distill

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/bborbe/errors"
)

// Driver runs the distill pipeline against a single source directory and
// writes one fully-regenerated output file.
//
// Fields are exported so callers (and tests) can replace any collaborator with
// a generated mock. Wiring is the responsibility of `pkg/factory`.
type Driver struct {
	// Parser reads source rule files from the source directory.
	Parser Parser
	// Runner sends per-section prompts to `claude --print`.
	Runner Runner
	// Writer commits the rendered output file atomically.
	Writer Writer
	// Stderr receives verbose-mode prompt/response dumps and warning lines.
	Stderr io.Writer
	// Verbose enables per-section prompt + response logging to Stderr.
	Verbose bool
	// Model is the value passed to `claude --model`.
	Model string
	// Title is the optional `# <text>` heading written under the auto-generated
	// warning comment. Empty = no title heading.
	Title string
}

// Run reads sourceDir, groups rules by section, invokes the runner once per
// section, and writes the assembled output file. The whole output is
// regenerated every run; any prior contents at outputPath are overwritten.
func (d *Driver) Run(ctx context.Context, sourceDir, outputPath string) error {
	rules, err := d.Parser.Parse(ctx, sourceDir)
	if err != nil {
		return err
	}
	if err := checkDuplicates(ctx, rules); err != nil {
		return err
	}
	groups, sectionOrder := groupBySection(filterEnabled(rules))
	compressed := map[string]string{}
	for _, section := range sectionOrder {
		body, err := d.runSection(ctx, section, groups[section])
		if err != nil {
			return err
		}
		compressed[section] = body
	}
	output := assembleOutput(sourceDir, outputPath, d.Title, sectionOrder, compressed)
	if err := d.Writer.Write(ctx, outputPath, output); err != nil {
		return err
	}
	return nil
}

func (d *Driver) runSection(ctx context.Context, section string, rules []Rule) (string, error) {
	bodies := make([]RuleBody, 0, len(rules))
	for _, r := range rules {
		bodies = append(bodies, RuleBody{ID: r.ID, Body: r.Body})
	}
	prompt := BuildPrompt(bodies)
	if d.Verbose {
		fmt.Fprintf(d.Stderr, "\n--- distill prompt section=%q ---\n%s\n", section, prompt)
	}
	body, err := d.Runner.Run(ctx, d.Model, prompt)
	if err != nil {
		return "", errors.Wrapf(ctx, err, "claude run section=%q", section)
	}
	if d.Verbose {
		fmt.Fprintf(d.Stderr, "\n--- distill response section=%q ---\n%s\n", section, body)
	}
	return body, nil
}

func filterEnabled(rules []Rule) []Rule {
	out := make([]Rule, 0, len(rules))
	for _, r := range rules {
		if r.Disabled {
			continue
		}
		out = append(out, r)
	}
	return out
}

// groupBySection returns rules grouped by section AND the section order. A
// section's position is determined by the minimum `Order` among its rules,
// with ties broken alphabetically.
func groupBySection(rules []Rule) (map[string][]Rule, []string) {
	groups := map[string][]Rule{}
	minOrder := map[string]int{}
	for _, r := range rules {
		groups[r.Section] = append(groups[r.Section], r)
		if existing, ok := minOrder[r.Section]; !ok || r.Order < existing {
			minOrder[r.Section] = r.Order
		}
	}
	sections := make([]string, 0, len(groups))
	for section := range groups {
		sections = append(sections, section)
	}
	sort.Slice(sections, func(i, j int) bool {
		a, b := sections[i], sections[j]
		if minOrder[a] != minOrder[b] {
			return minOrder[a] < minOrder[b]
		}
		return a < b
	})
	return groups, sections
}

func assembleOutput(
	sourceDir, outputPath, title string,
	sections []string,
	compressed map[string]string,
) string {
	var b strings.Builder
	b.WriteString("<!--\n")
	b.WriteString("  AUTO-GENERATED by distill — do not edit by hand.\n")
	fmt.Fprintf(&b, "  Source: %s\n", sourceDir)
	fmt.Fprintf(&b, "  Regenerate: distill --source %s --output %s\n", sourceDir, outputPath)
	b.WriteString("-->\n")
	if title != "" {
		b.WriteString("\n# ")
		b.WriteString(title)
		b.WriteString("\n")
	}
	for _, section := range sections {
		b.WriteString("\n## ")
		b.WriteString(section)
		b.WriteString("\n\n")
		body := strings.TrimRight(compressed[section], "\n")
		if body != "" {
			b.WriteString(body)
			b.WriteString("\n")
		}
	}
	return b.String()
}

func checkDuplicates(ctx context.Context, rules []Rule) error {
	type key struct {
		s string
		o int
		i string
	}
	seen := map[key]string{}
	for _, r := range rules {
		k := key{r.Section, r.Order, r.ID}
		if prev, ok := seen[k]; ok {
			return errors.Errorf(ctx,
				"duplicate (section=%q, order=%d, id=%q) in %q and %q",
				r.Section, r.Order, r.ID, prev, r.Path)
		}
		seen[k] = r.Path
	}
	return nil
}

// ExitCode maps an error returned from Run to a numeric exit code per
// docs/spec.md "Error Cases". Nil → 0, anything else → 1. Exit code 2 (usage)
// is the caller's concern in main.
func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	return 1
}
